<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-5EA9CPP" name="TestSuiteA.TestA" tests="4" failures="0" timestamp="2022-07-24T15:54:24 EDT" time="0.016" errors="1">
  <testcase name="init" time="0.016" classname="TestSuiteA.TestA">
    <error type="java.io.FileNotFoundException" message="C:\Users\haris\eclipse-workspace\HarisFramework\Project.properties (The system cannot find the file specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\haris\eclipse-workspace\HarisFramework\Project.properties (The system cannot find the file specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at Utilities.BaseClass.getProperties(BaseClass.java:129)
at Utilities.BaseClass.init(BaseClass.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
at org.testng.TestRunner.beforeRun(TestRunner.java:613)
at org.testng.TestRunner.run(TestRunner.java:584)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- init -->
  <testcase name="testA" time="0.000" classname="TestSuiteA.TestA">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testBMOLoginPage" time="0.000" classname="TestSuiteA.TestA">
    <skipped/>
  </testcase> <!-- testBMOLoginPage -->
  <testcase name="testPernalForm" time="0.000" classname="TestSuiteA.TestA">
    <skipped/>
  </testcase> <!-- testPernalForm -->
</testsuite> <!-- TestSuiteA.TestA -->
